### ISSUE TITLE
[Feature request] Style Setting Ideas

### ISSUE THREAD

**Issue by Minus10Celcius** [Erallie/colored-candy#1]
Maybe, you could add a setting to change and modify the hue, saturation and lighting! (e,g, change hue by 0.089)

**Comment by Erallie** [comment]
Modify the hue, saturation, and lightness for which thing? The background colors? Or the generated pseudo-accent colors?

The hue for everything is based off of the accent color that you choose under **Settings → Appearance → Accent color**. But the saturation and lightness for the background colors are fixed, and the saturation and lightness for the pseudo-accent colors are restricted, to ensure there is enough contrast for readability purposes in both the dark and light themes. I could *potentially* allow users to modify the background lightness and saturation by a certain amount, but I'd probably have to put a limit on that too, for readability's sake.

And I'm guessing this would use a plugin to add settings for it?

**Comment by Minus10Celcius** [comment]
Yes, style settings is a plugin

You can modify the background colors! But it is your theme after all!!

**Comment by Erallie** [comment]
I've decided to add this feature, once I set up integration with the Style Settings plugin.

**Comment by Erallie** [comment]
@Minus10Celcius I just pushed an update for the background lightness. I'm not sure whether to call this "Background lightness modifier" or just "Background-to-text contrast".

It will need more testing to make sure it's all good though.

**Comment by ElsaTam** [comment]
It's a really good feature idea.

I have one thought about it. More a design reflection than an issue.
Thing is, as soon as your accent color is set to grey (red = blue = green), the hue value that you retrieve is always 0, for the red. I don't think you can do anything about it. So there was no way to create a grey palette with your theme.
Unless... you allow user to change the saturation. And with a feature adjusting the saturation of the background, it could have been a workaround. The choice to not allow a full 0% saturation with this setting is good. But I just wonder if, later, you choose to add the possibility to make a grey palette, how would they coexist? It's just a thought, so you can think about that early enough in the design process.

Otherwise, the feature itself is tested and validated on my end! Amazing!
And I like "Background-to-text contrast". Since you also change the saturation "Background lightness modifier" would be misleading I think.

**Comment by Erallie** [comment]
> I have one thought about it. More a design reflection than an issue.
> Thing is, as soon as your accent color is set to grey (red = blue = green), the hue value that you retrieve is always 0, for the red. I don't think you can do anything about it. So there was no way to create a grey palette with your theme.
> Unless... you allow user to change the saturation. And with a feature adjusting the saturation of the background, it could have been a workaround. The choice to not allow a full 0% saturation with this setting is good. But I just wonder if, later, you choose to add the possibility to make a grey palette, how would they coexist? It's just a thought, so you can think about that early enough in the design process.

@ElsaTam Can you create a new issue with this feature request?

Also, thank you for testing it out! I will wait a little bit to see if @Minus10Celcius has anything to say about it. Otherwise, I will close this issue. :)
